blueprint:
  name: Zigbee2MQTT - Tuya TS0046 6-Button switch 
  domain: automation
  input:
    switch:
      name: TS0046 Switch
      description: Tuya 6-Button Scene Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_1_single_press:
      name: Single Press - Button 1
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 double press
      default: []
      selector:
        action: {}
    button_1_held:
      name: Hold - Button 1
      description: Action to run on button 1 held for 5 seconds
      default: []
      selector:
        action: {}
    button_2_single_press:
      name: Single Press - Button 2
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 double press
      default: []
      selector:
        action: {}
    button_2_held:
      name: Hold - Button 2
      description: Action to run on button 2 held for 5 seconds
      default: []
      selector:
        action: {}
    button_3_single_press:
      name: Single Press - Button 3
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 double press
      default: []
      selector:
        action: {}
    button_3_held:
      name: Hold - Button 3
      description: Action to run on button 3 held for 5 seconds
      default: []
      selector:
        action: {}
    button_4_single_press:
      name: Single Press - Button 4
      description: Action to run on button 4 single press
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: Double Press - Button 4
      description: Action to run on button 4 double press
      default: []
      selector:
        action: {}
    button_4_held:
      name: Hold - Button 4
      description: Action to run on button 4 held for 5 seconds
      default: []
      selector:
        action: {}
    button_5_single_press:
      name: Single Press - Button 5
      description: Action to run on button 5 single press
      default: []
      selector:
        action: {}
    button_5_double_press:
      name: Double Press - Button 5
      description: Action to run on button 5 double press
      default: []
      selector:
        action: {}
    button_5_held:
      name: Hold - Button 5
      description: Action to run on button 5 held for 5 seconds
      default: []
      selector:
        action: {}
    button_6_single_press:
      name: Single Press - Button 6
      description: Action to run on button 6 single press
      default: []
      selector:
        action: {}
    button_6_double_press:
      name: Double Press - Button 6
      description: Action to run on button 6 double press
      default: []
      selector:
        action: {}
    button_6_held:
      name: Hold - Button 6
      description: Action to run on button 6 held for 5 seconds
      default: []
      selector:
        action: {} 
mode: single
max_exceeded: silent
variables:
  command: '{{ trigger.to_state.state }}'
trigger:
- platform: state
  entity_id: !input 'switch'
  to:
    - '1_single'
    - '1_double'
    - '1_hold'
    - '2_single'
    - '2_double'
    - '2_hold'
    - '3_single'
    - '3_double'
    - '3_hold'
    - '4_single'
    - '4_double'
    - '4_hold'
    - '5_single'
    - '5_double'
    - '5_hold'
    - '6_single'
    - '6_double'
    - '6_hold'
action:
  - choose:
    - conditions:
      - '{{ command == ''1_single'' }}'
      sequence: !input 'button_1_single_press'
    - conditions:
      - '{{ command == ''1_double'' }}'
      sequence: !input 'button_1_double_press'
    - conditions:
      - '{{ command == ''1_hold'' }}'
      sequence: !input 'button_1_held'
    - conditions:
      - '{{ command == ''2_single'' }}'
      sequence: !input 'button_2_single_press'
    - conditions:
      - '{{ command == ''2_double'' }}'
      sequence: !input 'button_2_double_press'
    - conditions:
      - '{{ command == ''2_hold'' }}'
      sequence: !input 'button_2_held'
    - conditions:
      - '{{ command == ''3_single'' }}'
      sequence: !input 'button_3_single_press'
    - conditions:
      - '{{ command == ''3_double'' }}'
      sequence: !input 'button_3_double_press'
    - conditions:
      - '{{ command == ''3_hold'' }}'
      sequence: !input 'button_3_held'
    - conditions:
      - '{{ command == ''4_single'' }}'
      sequence: !input 'button_4_single_press'
    - conditions:
      - '{{ command == ''4_double'' }}'
      sequence: !input 'button_4_double_press'
    - conditions:
      - '{{ command == ''4_hold'' }}'
      sequence: !input 'button_4_held'
    - conditions:
      - '{{ command == ''5_single'' }}'
      sequence: !input 'button_5_single_press'
    - conditions:
      - '{{ command == ''5_double'' }}'
      sequence: !input 'button_5_double_press'
    - conditions:
      - '{{ command == ''5_hold'' }}'
      sequence: !input 'button_5_held' 
    - conditions:
      - '{{ command == ''6_single'' }}'
      sequence: !input 'button_6_single_press'
    - conditions:
      - '{{ command == ''6_double'' }}'
      sequence: !input 'button_6_double_press'
    - conditions:
      - '{{ command == ''6_hold'' }}'
      sequence: !input 'button_6_held'      
